#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
host=$(hostname)
if [ "$host" == "ubuntu" ]; then
  source $DIR/uenv/bin/activate
else
  source $DIR/.env/bin/activate
fi
python $DIR/snap.py $*
